name: YMSQLTest

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docker'
    - '.github'

jobs:
  Tests:
    runs-on:
      ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: init mysql_ymsql
      run: sudo docker-compose up -d mysql_ymsql

    - name: init apache_ymsql
      run: sudo docker-compose up -d apache_ymsql

    - name: init utils_ymsql
      run: sudo docker-compose up -d utils_ymsql

    - name: run tests
      run: sudo docker exec utils_ymsql /bin/sh -c 'cd var/www/ && ./vendor/bin/phpunit ./tests/VSQLTest.php'
